### PR TITLE
Allows sliderStyle, tooltipStyle to be a Function

### PR DESCRIPTION
**Pull request by bakatz**
I'm not sure why this PR generated such a large diff (possibly line ending issues?) but I just modified tooltipStyles() and sliderStyles() to allow a user defined function to be used to calculate the style object.

The change:
```
if (Array.isArray(this.tooltipStyle)) {
          return this.isRange ? this.tooltipStyle : this.tooltipStyle[1]
        } +else if (typeof this.tooltipStyle === 'function') {
           + return this.tooltipStyle(this.val)
         + } else {
          return this.isRange ? [this.tooltipStyle, this.tooltipStyle] : this.tooltipStyle
        }
```
Example of how I'm using sliderStyle:
```
const sliderBackgroundColors = [
  'black',
  'red',
  'brown',
  'orange',
  'yellow',
  'green'
]
const backgroundColorIndex = value === 0 ? 0 : (value - 1)
const newBackgroundColor = sliderBackgroundColors[backgroundColorIndex]
return {
  backgroundColor: newBackgroundColor
}
```

### CODE REVIEW

**Comment by bakatz** [comment]
Thanks for the quick turnaround on this one @NightCatSama - when will it be released to NPM?

**Comment by NightCatSama** [comment]
Wait a moment, I need to test and modify the document.

**Comment by NightCatSama** [comment]
And I found that you comment a line of code.
```js
time || this.$refs.process.offsetWidth
```

I know this line of code is weird, but it's necessary.

Because the browser merges style changes, just like:
```js
elem.style.transitionDuration = '0.5s' // this line will not work
elem.style.transform = 'translateX(100px)'
elem.style.transitionDuration = '0s'
```
```js
elem.style.transitionDuration = '0.5s' // this line will work
elem.style.transform = 'translateX(100px)'
elem.offsetWidth;
elem.style.transitionDuration = '0s'
```

I know this is not elegant, if you have a good solution, hope to submit or tell me. 

Finally, thank you for your congratulation on this project.

**Comment by NightCatSama** [comment]
please update to `@2.4.7`

**Comment by bakatz** [comment]
Gotcha - explanation makes sense. I'll update to 2.4.7 now, thanks!

**Pull request merged**
