### PR TITLE
Stop @callback being fired on external changes to the value.

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Fixes issue #39

### CODE REVIEW

**Comment by NightCatSama** [comment]
Thank you for your PR, it's great. 

But leave the third parameter blank ( `this.flag || this.setValue(val, true)` ), which is for the component to have an animation when modifying the value of the parent component.

`src/vue-slider2.vue` and `example/src/vue-slider/vue-slider2.vue` are the same, this inconsistency is because the last time I changed the order of parameters and I think do not need to send a new version of the lead.

You only need to modify the example inside.

I will wait for you to remove the third parameter and merge this PR.

**Comment by dobromir-hristov** [comment]
Do you want me to equalize the two files, because in one of them speed is the second parameter and I have to pass this.speed or null.

**Comment by NightCatSama** [comment]
Yes, so the `example/src/vue-slider/vue-slider2.vue` is the latest.  you only need to modify it.

**Comment by dobromir-hristov** [comment]
Well OK but what will change the `src/vue-slider2.vue` ? Do you have an automated task or something?

**Comment by NightCatSama** [comment]
I did not do automated processing, just copy. :sweat_smile:

So you can cover it over the past from `example/.../vue-slider2.vue`.

**Comment by dobromir-hristov** [comment]
Maybe have only one file and in the example just import that one? `import Vue-slider form '../../src/index'`

**Comment by dobromir-hristov** [comment]
Should be OK now.

**Comment by NightCatSama** [comment]
Sorry for so long to reply, I hope that the example and packaged separately, but there is no good way to deal with, maybe later will be optimized. 

Thank you once again.

**Pull request merged**
